import { siteConfig } from '@/config/site'
import { routing } from '@/lib/i18n/routing';
import type { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  const disallow = routing.locales.flatMap(lang => {
    return siteConfig.routes.authRoutes.flatMap(route => {
      const base = lang === routing.defaultLocale ? route : `/${lang}${route}`

      return [
        `${base}`,
        `${base}/*`,
      ]
    })
  })

  const blockUserAgents = [
    '008',
    'Alexibot',
    'ApocalXExplorerBot',
    'asterias',
    'BackDoorBot/1.0',
    'BizInformation',
    'Black Hole',
    'BlowFish/1.0',
    'BotALot',
    'BuiltBotTough',
    'Bullseye/1.0',
    'BunnySlippers',
    'Cegbfeieh',
    'CheeseBot',
    'CherryPicker',
    'CherryPickerElite/1.0',
    'CherryPickerSE/1.0',
    'CopyRightCheck',
    'cosmos',
    'Crescent',
    'Crescent Internet ToolPak HTTP OLE Control v.1.0',
    'DISCo Pump 3.1',
    'DittoSpyder',
    'dotbot',
    'EmailCollector',
    'EmailSiphon',
    'EmailWolf',
    'EroCrawler',
    'ExtractorPro',
    'Foobot',
    'Harvest/1.5',
    'hloader',
    'httplib',
    'HTTrack',
    'HTTrack 3.0',
    'humanlinks',
    'Igentia',
    'InfoNaviRobot',
    'JennyBot',
    'Kenjin Spider',
    'LexiBot',
    'libWeb/clsHTTP',
    'LinkextractorPro',
    'LinkScan/8.1a Unix',
    'LinkWalker',
    'lwp-trivial',
    'lwp-trivial/1.34',
    'Mata Hari',
    'Microsoft URL Control - 5.01.4511',
    'Microsoft URL Control - 6.00.8169',
    'MIIxpc',
    'MIIxpc/4.2',
    'Mister PiX',
    'MJ12bot',
    'MLBot',
    'moget',
    'moget/2.1',
    'MS Search 4.0 Robot',
    'MS Search 5.0 Robot',
    'Naverbot',
    'NetAnts',
    'NetAttache',
    'NetAttache Light 1.1',
    'NetMechanic',
    'NICErsPRO',
    'Offline Explorer',
    'Openfind',
    'Openfind data gathere',
    'ProPowerBot/2.14',
    'ProWebWalker',
    'psbot',
    'QuepasaCreep',
    'QueryN Metasearch',
    'RepoMonkey',
    'RepoMonkey Bait & Tackle/v1.01',
    'RMA',
    'SightupBot',
    'SiteBot',
    'SiteSnagger',
    'Sogou web spider',
    'sosospider',
    'SpankBot',
    'spanner',
    'Speedy',
    'suggybot',
    'SuperBot',
    'SuperBot/2.6',
    'suzuran',
    'Szukacz/1.4',
    'Teleport',
    'Telesoft',
    'The Intraformant',
    'TheNomad',
    'TightTwatBot',
    'Titan',
    'toCrawl/UrlDispatcher',
    'True_Robot',
    'True_Robot/1.0',
    'turingos',
    'TurnitinBot',
    'URLy Warning',
    'VCI',
    'VCI WebViewer VCI WebViewer Win32',
    'Web Image Collector',
    'WebAuto',
    'WebBandit',
    'WebBandit/3.50',
    'WebCopier',
    'webcopy',
    'WebEnhancer',
    'WebmasterWorldForumBot',
    'webmirror',
    'WebReaper',
    'WebSauger',
    'website extractor',
    'Website Quester',
    'Webster Pro',
    'WebStripper',
    'WebStripper/2.02',
    'WebZip',
    'WebZip/4.0',
    'Wget',
    'Wget/1.5.3',
    'Wget/1.6',
    'WikioFeedBot',
    'wikiwix-bot-3.0',
    'WinHTTrack',
    'WWW-Collector-E',
    'Xenu\'s',
    'Xenu\'s Link Sleuth 1.1c',
    'YRSPider',
    'Zeus',
  ];

  return {
    sitemap: `${siteConfig.url}/sitemaps/sitemap.xml`,
    rules: [
      {
        userAgent: blockUserAgents,
        disallow: ['/'],
      },
      {
        userAgent: '*',
        allow: '/',
        disallow,
      },
    ]
  }
}